"""empty message

Revision ID: 25e2b6998b03
Revises: 325c5ed2f9ea
Create Date: 2023-12-20 00:13:58.477798

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '25e2b6998b03'
down_revision = '325c5ed2f9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_appliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('KITCHEN', 'LAUNDRY', 'CLEANING', 'ENTERTAINMENT', 'HOME_OFFICE', name='householdappliancetype'), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household_appliances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_appliances_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_appliances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_appliances_name'))

    op.drop_table('household_appliances')
    # ### end Alembic commands ###
