"""Added post tag table

Revision ID: 325c5ed2f9ea
Revises: fe19c5c6f02a
Create Date: 2023-11-23 02:20:06.487490

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '325c5ed2f9ea'
down_revision = 'fe19c5c6f02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
