"""Added about me and last seen columns

Revision ID: 32602bb7d51f
Revises: d095827280a2
Create Date: 2023-11-12 19:05:38.329751

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '32602bb7d51f'
down_revision = 'd095827280a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
