"""Added missed enabled field

Revision ID: 363132978280
Revises: f7dc6a40ac5e
Create Date: 2023-11-22 22:47:17.607165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363132978280'
down_revision = 'f7dc6a40ac5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
